sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t toniher/docker-rpi-mariadb .
# test image
- docker run toniher/docker-rpi-mariadb mysql --version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV MYSQL_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag toniher/docker-rpi-mariadb toniher/docker-rpi-mariadb:$TAG
    docker push toniher/docker-rpi-mariadb:$TAG
    docker push toniher/docker-rpi-mariadb
  fi
